// Generated by CoffeeScript 1.6.2
(function() {
  this.Keyboard = (function() {
    Keyboard.prototype.key = null;

    Keyboard.prototype.keyCode = null;

    Keyboard.prototype.map = {
      0x0: 81,
      0x1: 87,
      0x2: 69,
      0x3: 65,
      0x4: 83,
      0x5: 68,
      0x6: 90,
      0x7: 88,
      0x8: 67,
      0x9: 82,
      0xa: 70,
      0xb: 86,
      0xc: 84,
      0xd: 71,
      0xe: 66,
      0xf: 32
    };

    Keyboard.prototype.await_list = [];

    function Keyboard() {
      document.addEventListener("keydown", this);
      document.addEventListener("keyup", this);
    }

    Keyboard.prototype.await = function(callback) {
      console.log("AWAIT");
      return this.await_list.push(callback);
    };

    Keyboard.prototype.await_process = function() {
      var callback;

      while (callback = this.await_list.shift()) {
        callback(this.key);
      }
      return true;
    };

    Keyboard.prototype.getCode = function(key) {
      var i, j, _ref;

      _ref = this.map;
      for (i in _ref) {
        j = _ref[i];
        if (j === key) {
          return +i;
        }
      }
    };

    Keyboard.prototype.handleEvent = function(e) {
      switch (e.type) {
        case "keydown":
          if (e.keyCode !== this.keyCode && !this.key) {
            if (this.key = this.getCode(e.keyCode)) {
              this.keyCode = e.keyCode;
              return this.await_process();
            } else {
              this.key = null;
              return this.keyCode = null;
            }
          }
          break;
        case "keyup":
          if (e.keyCode === this.keyCode) {
            this.key = null;
            return this.keyCode = null;
          }
      }
    };

    return Keyboard;

  })();

}).call(this);
