// Generated by CoffeeScript 1.6.2
(function() {
  this.ROMParser = (function() {
    ROMParser.prototype.file = null;

    ROMParser.prototype.url = null;

    function ROMParser(file, callback) {
      if (callback == null) {
        callback = function() {};
      }
      if (file != null) {
        this.loadFile(file, callback);
      }
    }

    ROMParser.prototype.loadFile = function(file, callback) {
      var _this = this;

      if (callback == null) {
        callback = function() {};
      }
      this.url = file;
      return this.ajax(file, function(xhr) {
        var buffer;

        buffer = xhr.response;
        _this.file = new Uint8Array(buffer);
        return callback(_this);
      });
    };

    ROMParser.prototype.ajax = function(url, callback) {
      var xhr;

      if (callback == null) {
        callback = function() {};
      }
      xhr = new XMLHttpRequest;
      xhr.open('get', url, true);
      xhr.onload = function() {
        return callback(xhr);
      };
      xhr.responseType = "arraybuffer";
      xhr.send(null);
      return xhr;
    };

    return ROMParser;

  })();

}).call(this);
