// Generated by CoffeeScript 1.6.2
(function() {
  this.Sound = (function() {
    Sound.prototype.audioContext = null;

    Sound.prototype.context = null;

    Sound.prototype.running = false;

    function Sound() {
      this.audioContext = new window.webkitAudioContext;
    }

    Sound.prototype.beep = function() {
      var _this = this;

      this.start();
      return setTimeout(function() {
        return _this.stop();
      }, 100);
    };

    Sound.prototype.start = function() {
      if (!this.running) {
        this.context = this.audioContext.createOscillator();
        this.context.connect(this.audioContext.destination);
        this.context.type = 3;
        this.context.noteOn(0);
        return this.running = true;
      }
    };

    Sound.prototype.stop = function() {
      this.running = false;
      return this.context.noteOff(0);
    };

    return Sound;

  })();

}).call(this);
